### ISSUE TITLE
请问可否添加一个当版本不匹配时自动从预设的链接下载文件并打开？

### ISSUE THREAD

**Issue by Max66888** [ELDment/Csgo-Server-Launcher-Python#3]
请问可否添加一个当版本不匹配时自动从预设的链接下载文件并打开？
就是想有一个自动更新，或者设置成云下发配置

**Comment by ELDment** [comment]
我的思路是：先下载个fastdl版本号到本地，每次启动启动器的时候读取这个版本号，和最新云端fastdl版本号进行对比。
但是我目前没有时间维护这个项目，你可以自己尝试一下<3
